const TODOS = {
  UPDATE_TODOS: 'TODOS_UPDATE_TODOS',
};

const NEWS_FEED = {
  LOAD_NEWS: 'NEWS_FEED_LOAD_NEWS',
  LOAD_NEWS_SUCCESS: 'NEWS_FEED_LOAD_NEWS_SUCCESS',
  LOAD_NEWS_FAIL: 'NEWS_FEED_LOAD_NEWS_FAIL',
};

const CALENDAR = {
  UPDATE_CALENDAR: 'CALENDAR_UPDATE_CALENDAR',
};

const AUTH = {
  AUTH: 'AUTH',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAIL: 'AUTH_FAIL',
};

const USER = {
  SET_LOGIN_MODE: 'USER_SET_LOGIN_MODE',
};

export { TODOS, NEWS_FEED, CALENDAR, AUTH, USER };
