const TODOS = {
  UPDATE_TODOS: 'TODOS_UPDATE_TODOS',
  POST_TODO: 'TODOS_POST_TODO',
  POST_TODO_SUCCESS: 'TODOS_POST_TODO_SUCCESS',
  POST_TODO_FAIL: 'TODOS_POST_TODO_FAIL',
  LOAD_TODOS: 'TODOS_LOAD_TODOS',
  LOAD_TODOS_SUCCESS: 'TODOS_LOAD_TODOS_SUCCESS',
  LOAD_TODOS_FAIL: 'TODOS_LOAD_TODOS_FAIL',
  DELETE_TODO: 'TODOS_DELETE_TODO',
  DELETE_TODO_SUCCESS: 'TODOS_DELETE_TODO_SUCCESS',
  DELETE_TODO_FAIL: 'TODOS_DELETE_TODO_FAIL',
};

const NEWS_FEED = {
  LOAD_NEWS: 'NEWS_FEED_LOAD_NEWS',
  LOAD_NEWS_SUCCESS: 'NEWS_FEED_LOAD_NEWS_SUCCESS',
  LOAD_NEWS_FAIL: 'NEWS_FEED_LOAD_NEWS_FAIL',
};

const CALENDAR = {
  UPDATE_CALENDAR: 'CALENDAR_UPDATE_CALENDAR',
};

const AUTH = {
  AUTH: 'AUTH',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAIL: 'AUTH_FAIL',
  RESET_ERROR: 'AUTH_RESET_ERROR',
};

const USER = {
  SET_LOGIN_MODE: 'USER_SET_LOGIN_MODE',
};

export { TODOS, NEWS_FEED, CALENDAR, AUTH, USER };
