const TODOS = {
  UPDATE_TODOS: 'TODOS_UPDATE_TODOS',
  POST_TODO: 'TODOS_POST_TODO',
  POST_TODO_SUCCESS: 'TODOS_POST_TODO_SUCCESS',
  POST_TODO_FAIL: 'TODOS_POST_TODO_FAIL',
  LOAD_TODOS: 'TODOS_LOAD_TODOS',
  LOAD_TODOS_SUCCESS: 'TODOS_LOAD_TODOS_SUCCESS',
  LOAD_TODOS_FAIL: 'TODOS_LOAD_TODOS_FAIL',
  DELETE_TODO: 'TODOS_DELETE_TODO',
  DELETE_TODO_SUCCESS: 'TODOS_DELETE_TODO_SUCCESS',
  DELETE_TODO_FAIL: 'TODOS_DELETE_TODO_FAIL',
  CHECK_TODO: 'TODOS_CHECK_TODO',
  PATCH_CHECK_TODO: 'TODOS_PATCH_CHECK_TODO',
  PATCH_CHECK_TODO_SUCCESS: 'TODOS_PATCH_CHECK_TODO_SUCCESS',
  PATCH_CHECK_TODO_FAIL: 'TODOS_PATCH_CHECK_TODO_FAIL',
};

const NEWS_FEED = {
  LOAD_NEWS: 'NEWS_FEED_LOAD_NEWS',
  LOAD_NEWS_SUCCESS: 'NEWS_FEED_LOAD_NEWS_SUCCESS',
  LOAD_NEWS_FAIL: 'NEWS_FEED_LOAD_NEWS_FAIL',
};

const CALENDAR = {
  UPDATE_CALENDAR: 'CALENDAR_UPDATE_CALENDAR',
  LOAD_APPOINTMENTS: 'CALENDAR_LOAD_APPOINTMENTS',
  LOAD_APPOINTMENTS_SUCCESS: 'CALENDAR_LOAD_APPOINTMENTS_SUCCESS',
  LOAD_APPOINTMENTS_FAIL: 'CALENDAR_LOAD_APPOINTMENTS_FAIL',
  POST_APPOINTMENT: 'CALENDAR_POST_APPOINTMENT',
  POST_APPOINTMENT_SUCCESS: 'CALENDAR_POST_APPOINTMENT_SUCCESS',
  POST_APPOINTMENT_FAIL: 'CALENDAR_POST_APPOINTMENT_FAIL',
  UPDATE_APPOINTMENT: 'CALENDAR_UPDATE_APPOINTMENT',
  UPDATE_APPOINTMENT_SUCCESS: 'CALENDAR_UPDATE_APPOINTMENT_SUCCESS',
  UPDATE_APPOINTMENT_FAIL: 'CALENDAR_UPDATE_APPOINTMENT_FAIL',
  DELETE_APPOINTMENT: 'CALENDAR_DELETE_APPOINTMENT',
  DELETE_APPOINTMENT_SUCCESS: 'CALENDAR_DELETE_APPOINTMENT_SUCCESS',
  DELETE_APPOINTMENT_FAIL: 'CALENDAR_DELETE_APPOINTMENT_FAIL',
};

const AUTH = {
  AUTH: 'AUTH',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAIL: 'AUTH_FAIL',
  RESET_ERROR: 'AUTH_RESET_ERROR',
  LOGOUT: 'AUTH_LOGOUT',
};

const USER = {
  SET_LOGIN_MODE: 'USER_SET_LOGIN_MODE',
};

export { TODOS, NEWS_FEED, CALENDAR, AUTH, USER };
